### ISSUE TITLE
Sortare disctutii / raspunsuri

### ISSUE THREAD

**Issue by mehanix** [mehanix/OurReddit#20]

**Comment by Stefan-Radu** [comment]
[] sortare dupa data 
[] sortare alfabetica

**Comment by Stefan-Radu** [comment]
Pt. Subjects:
- [ ] sortare dupa data
- [ ] sortare alfabetica

Pt. mesaje
- [ ] sortare dupa data
- [ ] sortare dupa like-uri (most popular gen) ? (pt asta trb sa adaugam feature de like la comments)
